language: c

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-linux-gnueabihf
  - arm-linux-gnueabihf-gcc --version
  - sudo apt-get install bc

before_script:
  - export KERN_V=4.4.8
  - export BUILD_V=-ti-rt-r22

  - export MYHOME=$PWD
  - wget https://github.com/beagleboard/linux/archive/$KERN_V$BUILD_V.tar.gz
  - tar xf $KERN_V$BUILD_V.tar.gz
  - export DST_KERNEL=$PWD/linux-$KERN_V$BUILD_V

script:
  - cd $DST_KERNEL
  
  - export ARCH=arm
  - export CROSS_COMPILE=arm-linux-gnueabihf-
 
  - sudo make ARCH=arm LOCALVERSION=$BUILD_V CROSS_COMPILE=arm-linux-gnueabihf- mrproper 
  - wget -c http://rcn-ee.net/deb/jessie-armhf/v$KERN_V$BUILD_V/defconfig -O .config
  - sudo make ARCH=arm LOCALVERSION=$BUILD_V CROSS_COMPILE=arm-linux-gnueabihf- modules

  - cd $MYHOME/

  - sudo chmod +x $DST_KERNEL/scripts/checkpatch.pl
  - sudo perl $DST_KERNEL/scripts/checkpatch.pl --no-tree -f $MYHOME/test_master_app/*
  - sudo perl $DST_KERNEL/scripts/checkpatch.pl --no-tree -f $MYHOME/slave_app/*
  - sudo perl $DST_KERNEL/scripts/checkpatch.pl --no-tree -f $MYHOME/driver/* 
  
  - sudo make
