language: c

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-linux-gnueabihf
  - arm-linux-gnueabihf-gcc --version
  - sudo apt-get install bc
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install libc6-i386 lib32stdc++6 lib32z1; fi

before_script:
  - export MYHOME=$PWD
  - wget https://github.com/beagleboard/linux/archive/4.4.8-ti-rt-r22.tar.gz
  - tar zvxf 4.4.8-ti-rt-r22.tar.gz
  - export DST_KERNEL=$PWD/linux-4.4.8-ti-rt-r22

script:
  - cd $DST_KERNEL
  
  - export ARCH=arm
  - export CROSS_COMPILE=arm-linux-gnueabihf-
  - export CFLAGS="-g3 -std=c99 -pedantic -Wall"
  - sudo make -j3 CFLAGS="-g3 -std=c99 -pedantic -Wall" ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- mrproper
  - sudo make -j3 CFLAGS="-g3 -std=c99 -pedantic -Wall" ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- omap2plus_defconfig
  - sudo make -j3 CFLAGS="-g3 -std=c99 -pedantic -Wall" ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- all

  - cd $MYHOME/
  - sudo make

