language: c
os:
  - linux

before_install:
  # Install linux headers
  -sudo apt-get update
  -sudo apt-get upgrade
  -sudo apt-get install linux-generic
  -sudo apt-get install linux-headers-$(shell uname -r)

install:
  # Install the arm32 cross-compiler
  -sudo apt-get install -y gcc-arm-linux-gnueabihf

script:
  -make


