language: c
os:
  - linux

before_install:
  # Install linux headers
  -sudo apt-get install -qq linux-headers-$(uname -r)

install:
  # Install the arm32 cross-compiler
  -sudo apt-get install -y gcc-arm-linux-gnueabihf

script:
  -make


